########################################
# CBMCSuite Default Configuration File #
# CBMCSuite Default Configuration File #
######################################## 

Plugin:
  Version: 1.0
  
  
PlayerJoin:

  Enable:
    MOTD: true
    PotionEffects: true
    JoinClear&Kit: true
    AdventureModeHub: true
    WelcomeBroadcast: true
    
  Messages:
    Welcome: $logo$ Welcome to $cbmc$, $player$!
    MOTD: Welcome back to $cbmc$, $player$! (Plugin $plugin$ By $devs$)
